name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d  # TSCCR: no entry for action: "peaceiris/actions-hugo"
        with:
          hugo-version: '0.115.0'
          extended: true

      - name: Build
        working-directory: ./docs
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935  # TSCCR: no entry for action: "peaceiris/actions-gh-pages"
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
