name: unit-tests-breaking-change-detector

permissions: read-all

on:
  pull_request:
    paths:
      - 'tools/breaking-change-detector/**'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '^1.19.1'

      - name: Build
        run: |
          cd tools/breaking-change-detector
          make clone OWNER_REPO=hashicorp/terraform-provider-google DEPTH=1
          make build OLD_REF=main NEW_REF=main

      - name: Test
        run: |
          cd tools/breaking-change-detector
          go test -v ./...
