name: TeamCity Unit Tests
permissions: read-all

on:
  workflow_call:
    inputs:
      repo:
        description: 'Repository for the matrix'
        required: true
        type: string

jobs:
  teamcity-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact-${{ inputs.repo }}
          path: artifacts

      - name: Unzip the artifacts and delete the zip
        run: |
          unzip artifacts/output.zip -d ./
          rm artifacts/output.zip

      - name: Setup Java
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: zulu
          java-version: 17
          java-package: jdk

      - name: Cache Maven files
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download TeamCity Tools
        run : |
          pwd
          cd .teamcity
          pwd
          make tools

      - name: Run TeamCity Tests
        run : |
          pwd
          cd .teamcity
          pwd
          make test